
import Header from "@/components/Header/Header.js"
import Footer from "@/components/Footer/Footer.js"

import { Cairo } from "next/font/google";
import "./globals.css";

const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["400", "700"],
  variable: "--font-cairo",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={cairo.variable}
      >

        <Header />
        <div>{children}</div>
        <Footer />


      </body>
    </html>
  );
}
